"""Remove account_manager

Revision ID: 69dd1dc0610e
Revises: 68e9512045bb
Create Date: 2025-12-04 11:40:27.842920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69dd1dc0610e'
down_revision = '68e9512045bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('account_manager')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_manager', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
