"""Initial B2B CRM schema creation

Revision ID: 56a8b9d88910
Revises: 
Create Date: 2025-12-03 23:07:57.300488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a8b9d88910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_reference', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_due_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('primary_contact', sa.String(length=255), nullable=True),
    sa.Column('account_manager', sa.String(length=100), nullable=True),
    sa.Column('team_members_json', sa.Text(), nullable=True),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_reference')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('activities_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('estimated_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('customer_form_data', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoice_line_items_invoice_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('invoices_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_login_attempts_email'))
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('opportunity_documents', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('opportunity_documents_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('opportunity_notes', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('opportunity_notes_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('proposal_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proposal_items_proposal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proposals', ['proposal_id'], ['id'])

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('versioned_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('versioned_snapshots_entity_type_entity_id_version_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versioned_snapshots', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('versioned_snapshots_entity_type_entity_id_version_number_key'), ['entity_type', 'entity_id', 'version_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('proposal_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proposal_items_proposal_id_fkey'), 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('opportunity_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_notes_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('opportunity_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_documents_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.create_index(batch_op.f('idx_login_attempts_email'), ['email'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoices_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoice_line_items_invoice_id_fkey'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('customer_form_data', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('estimated_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    op.drop_table('jobs')
    # ### end Alembic commands ###
